# Introduction to Numpy


 ## What is Numpy ?

*NumPy ek powerful Python library hai jo arrays, matrix aur numerical calculations ke liye use karta hai.*


## Installation of numpy

In [2]:
pip install numpy

 *pip install numpy ek command hai jo Python me NumPy library ko install karne ke liye use hoti hai*

## Import Numpy Library

In [3]:
import numpy as np

 #### NumPy library ko Python program me use karne ke liye load karna, aur uska short name np rakhna.

##### **import** :- *ka matlab hota hai library ko program me lana*
##### **numpy** :-  *ek Python library hai jo numbers, arrays, math operations ke liye use hoti hai*
##### **as np** :-  *ka matlab hai numpy ka short name np rakhna*

In [4]:
# print(dir(np))

## Numpy Array

### 1D Array
*Ye 1-Dimensional array hai Sirf ek row hoti hai.*
#### **print(arr)** = *Array ke sab elements ko print karta hai.*

In [5]:
arr = np.array([11,12,13,14,15,16,17])
print(arr)

[11 12 13 14 15 16 17]


### 2D Array (Matrix)
 *Ye 2D array hai (rows + columns)*

In [6]:
arr1 = np.array([[12,13,14,11],[15,124,15,15],[21,4,54,54]])
print(arr1)

[[ 12  13  14  11]
 [ 15 124  15  15]
 [ 21   4  54  54]]


### 3D Array (Single Block)
 *Ye 3-D array hai Matlab: 1 block, 4 rows, 3 columns*

In [7]:
arr2 = np.array([[[12,12,12],[11,42,52],[43,45,98],[3,5,5]]])
print(arr2)

[[[12 12 12]
  [11 42 52]
  [43 45 98]
  [ 3  5  5]]]


### 3D Array (Multiple Blocks)
*Jab ek array ke andar multiple 2D matrices (layers) hoti hain, to use Multiple Blocks bolte hain.*

In [9]:
arr3 = np.array([[[45,22,45,15],[58,54,55,45]],
                 [[45,84,43,54],[75,45,65,58]]])
print(arr3)

[[[45 22 45 15]
  [58 54 55 45]]

 [[45 84 43 54]
  [75 45 65 58]]]


### Array Indexing & Properties

In [42]:
arr1 = np.array([[[12,13,14,11],[15,124,15,15]],[[21,4,54,54],[54,54,24,78]]])
print(arr1)

[[[ 12  13  14  11]
  [ 15 124  15  15]]

 [[ 21   4  54  54]
  [ 54  54  24  78]]]


**print(arr1) :-** *Array ke sab elements ko print karta hai.*

In [41]:
arr1 = np.array([[[12,13,14,11],[15,124,15,15]],[[21,4,54,54],[54,54,24,78]]])
print(type(arr1)) 

<class 'numpy.ndarray'>


**type :-** *Ye batata hai array ka data type.*

In [38]:
arr1 = np.array([[[12,13,14,11],[15,124,15,15]],[[21,4,54,54],[54,54,24,78]]])
print(arr1.ndim)

3


**ndim :-** *Array ki dimension batata hai.*

In [11]:
arr1 = np.array([[[12,13,14,11],[15,124,15,15]],[[21,4,54,54],[54,54,24,78]]])
print(arr1.shape)
print(arr1)

(2, 2, 4)
[[[ 12  13  14  11]
  [ 15 124  15  15]]

 [[ 21   4  54  54]
  [ 54  54  24  78]]]


**Shape:-** *Matlab: 2 blocks (layers) Har block me 2 rows Har row me 4 columns*

In [40]:
arr1 = np.array([[[12,13,14,11],[15,124,15,15]],[[21,4,54,54],[54,54,24,78]]])
print(arr1.size)

16


**size:-** *total elements count karta hai ,Formula: blocks * rows * columns = 2 * 2 * 4 = 16*

## Numpy function
##### Array Creation Functions :- (array,zeros,ones,eye,full)
##### Mathematical Functions :-(sum,mean,max,min,sqrt)
##### Shape & Dimension Functions :-(ndim,shape,size)
##### Random Functions :- (random.rand,random.randint,random.randn)
##### Sequence Functions :- (arange,linspace)
##### Matrix Functions :- (dot,transpose)


### Array Creation Functions :-

In [22]:
a = np.array([1, 2, 3, 4])
a

array([1, 2, 3, 4])

**Array :-** *Array NumPy ka main data structure hota hai.Ye multiple values ko ek hi variable me store karta hai, aur sab values same data type ki hoti hain.*

In [18]:
arr = np.zeros((5,4))
arr

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

 **Zeros :-** *Jab hume pehle se empty array chahiye jisme values baad me fill karni ho, tab zeros() use karte hain.*

In [24]:
arr = np.ones((5,4))
arr

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

**Ones :-** *Jab hume default value 1 ke saath array initialize karna ho, tab ones() use karte hain.*

In [25]:
arr = np.eye(3,4)
arr

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.]])

**eye :-** *Identity Matrix wo matrix hoti hai jisme Diagonal elements = 1 ,Baaki sab elements = 0*

In [27]:
arr = np.full((3,4), 9)
arr

array([[9, 9, 9, 9],
       [9, 9, 9, 9],
       [9, 9, 9, 9]])

**Full :-** *jitna size tum do, usme har jagah same value fill ho jaati hai.*

### Mathematical Functions  :-



In [43]:
arr = np.array([10, 20, 30, 40])
print(arr.sum())

100


**sum :-** *array ke andar jitni bhi values hain, unka sum ek hi baar me mil jaata hai.*

In [45]:
arr = np.array([10, 20, 30, 40])
print(arr.mean())

25.0


**mean :-** *NumPy ka function hai ,jo array ka average (Arithmetic Mean) nikalta hai. Mean = (sab values ka sum) / (total values)*

In [46]:
arr = np.array([10, 45, 23, 90, 12])
print(arr.max())

90


**max :-** *jo array ke andar sabse badi (maximum) value nikalta hai.*

In [47]:
arr = np.array([10, 45, 23, 90, 12])
print(arr.min())

10


**min :-** *jo array ke andar sabse chhoti (minimum) value nikalta hai.*

In [49]:
arr = np.array([1, 4, 9, 16, 25])
print(np.sqrt(arr))

[1. 2. 3. 4. 5.]


**sqrt :-** *jo array ke har element ka square root nikalta hai.*

### Shape & Dimension Functions :-

In [50]:
arr = np.array([10, 20, 30])
print(arr.ndim)

1


**ndim :-** *jo array ki total dimensions batata hai.*

In [51]:
arr = np.array([[1,2,3],[4,5,6]])
print(arr.shape)

(2, 3)


**shape:-** *jo array ka structure / size batata hai.*

In [53]:
arr = np.array([10, 20, 30, 40])
print(arr.size)

4


**size:-** *jo array me total elements ki counting batata hai.*

### Random Functions :- (random.rand,random.randint,random.randn)

In [55]:
arr = np.random.rand(3,3)
print(arr)

[[0.87883978 0.65007382 0.43426245]
 [0.42325381 0.69727041 0.92455705]
 [0.02571247 0.16875903 0.29688035]]


**random.rand:-** *NumPy ka function hai
jo 0 se 1 ke beech random numbers generate karta hai.(postive value)*

In [59]:
arr = np.random.randint(10,100,(4,3))
print(arr)

[[41 79 53]
 [95 72 59]
 [65 71 97]
 [87 63 70]]


**random.randint :-** *random integers generate karta hai specified range ke andar.range :-(10,100)*

In [9]:
arr = np.random.randn(3,4)
print(arr)

[[ 0.72789563  0.58272438  0.8396922  -2.0559849 ]
 [-2.53380509 -2.8612097  -0.43464768 -0.50775433]
 [-0.16676571  0.19792704 -1.09394165  1.2666674 ]]


**random.randn :-** *normally distributed (Gaussian) random numbers generate karta hai,
Ye numbers negative aur positive dono ho sakte hain.0 sa 1 beech ma.*

### Sequence Functions :- 

In [64]:
arr = np.arange(0, 40, 2)   # (start, stop, step)
print(arr)

[ 0  2  4  6  8 10 12 14 16 18 20 22 24 26 28 30 32 34 36 38]


**arange :-** *start se leke stop tak numbers generate karo with step*

In [66]:
arr = np.linspace(0,20,5)  # (start,stop num)
print(arr)

[ 0.  5. 10. 15. 20.]


**linspace:-** *jo start aur stop ke beech evenly spaced numbers generate karta .*

### Matrix Functions :- 

In [67]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
result = np.dot(a, b)
print(result)

32


**dot:-** *Dot product (sum of products), Matrix multiplication*

In [68]:
arr= np.array([[1, 2, 3],[4, 5, 6]])
print(arr.T)

[[1 4]
 [2 5]
 [3 6]]


**transpose(T):-** *jo matrix ka rows aur columns swap karta hai.*

In [7]:
arr = np.array([10, 45, 23, 99, 34])
print(np.argmax(arr))

3


**argmax():-** *NumPy ka ek function hai jo array ke andar sabse badi (maximum) value ka index position batata hai.*

In [8]:
arr = np.array([10, 45, 23, 5, 34])
print(np.argmin(arr))

3


**argmin():-** *NumPy ka ek function hai jo array ke andar sabse chhoti (minimum) value ka index position batata hai.*

In [9]:
arr = np.array([10, 20, 30, 40, 50])
print(np.std(arr))

14.142135623730951


**std():-** *NumPy ka ek function hai jo Standard Deviation calculate karta hai.Data mean (average) se kitna spread / faila hua hai, uska measure hota hai.*

In [10]:
arr = np.array([[1, 2, 3],[4, 5, 6]])
print(arr.flatten())

[1 2 3 4 5 6]


**flatten():-** *NumPy ka function hai jo multi-dimensional array (2D, 3D, etc.) ko 1D array me convert kar deta hai.*

In [11]:
arr = np.array([[1, 2, 3],[4, 5, 6]])
print(arr.ravel())

[1 2 3 4 5 6]


**ravel():-** *Array ko flat banata hai, lekin zyada tar cases me original array ka “view” deta hai.*

In [12]:
arr = np.array([1, 2, 3, 4, 5, 6])
print(arr.reshape(2, 3))

[[1 2 3]
 [4 5 6]]


**reshape():-** *NumPy ka function hai jo array ka shape change karta hai.Data same rehta hai, sirf rows–columns ka structure change hota hai.*

In [14]:
arr = np.array([1, 2, 3, 4])
print(np.diag(arr))

[[1 0 0 0]
 [0 2 0 0]
 [0 0 3 0]
 [0 0 0 4]]


**diag():-** NumPy ka function hai jo diagonal elements ke saath kaam karta hai.

### Arithmetic Operations

In [4]:
a = np.array([10, 20, 30])
b = np.array([1, 2, 3])
print(a + b)

print(a - b)

print(a * b)

print(a / b)

[11 22 33]
[ 9 18 27]
[10 40 90]
[10. 10. 10.]


### Sort Array

In [8]:
arr = np.array([40, 10, 30, 20])
print(np.sort(arr))

[10 20 30 40]


## Difference Between NumPy Array and Python List

 *Python me data store karne ke liye List aur NumPy Array dono use hote hain.Dono ka kaam same lag sakta hai, lekin performance, usage aur power me kaafi difference hota hai.*

*Numpy perform faster for larger-scale mathematical operations while list slower for numerical computations due to per-element overheead.*

*Numpy supports advanced mathematical functions,linear algebra, broadcasting and multi-dimensional arrays list offers general-purpose methods like sort,count,and reverse.*

In [17]:
list1 = [1, 2, 3, 4]
array1 = np.array([1,2,3,4])
print("List Addition: ",list1 + list1)
print("Numpy array Addition : ", array1 +array1)


List Addition:  [1, 2, 3, 4, 1, 2, 3, 4]
Numpy array Addition :  [2 4 6 8]


*List repeat the values and give output .Numpy perfrom addition and give the sum of values in output.*

## Try these 4 question

* NumPy use karke 1 se 20 tak numbers ka array banao.**hint(np.arange())**

* Us array ko reshape karke 4 rows aur 5 columns ki matrix banao.     **hint(reshape())**

* Matrix me se:                                       **hint(  boolean indexing  ,mean())**

   * sabhi even numbers print karo

    * sabhi elements ka mean (average) nikalo

* Matrix ka transpose nikalo.         **hint(.T)**